### ISSUE TITLE
zad 6

### ISSUE THREAD

**Issue by mrzeszut** [MikolajZiolk/ZadaniaML_Kurs#23]
004b2268e5114307fa94ab596203e3a6ed1754d7
#22 
`Recipe` - czy na pewno wszystkie zastosowane zmienne są istotne i ważne w procesie prognozowania ozonu. Zgodnie z recipe wykluczono tylko `pm10` i `pm25`

Myślę, że jeden wniosek to za mało. Proszę pomyśleć. 

Proszę utworzyć z problemu branch, rozwiązać problem scalić nowy branch z main i zamknąć ten problem.  Zrobimy to na zajęciach. 

Bardzo ładny przepływ pracy `R->user->git->github`

**Comment by MikolajZiolk** [comment]
Pierwszy komentarz
